pull_request_rules:
  - name: Automatic merge when all status checks pass
    conditions:
      - author=snyk-bot
      - status-success=security/snyk (Bifravst)
      - status-success=tests (ubuntu-latest)
      - status-success=tests (macos-latest)
    actions:
      merge:
        method: rebase
        rebase_fallback: squash
        bot_account: bifravst-ci
      label:
        add:
         - mergify
      rebase:
        bot_account: bifravst-ci
