pull_request_rules:
  - name: Automatic merge when all status checks pass
    conditions:
      - status-success=security/snyk (Bifravst)
      - status-success=tests (ubuntu-latest)
      - status-success=tests (macos-latest)
    actions:
      label:
        add:
         - mergify
      rebase:
        bot_account: bifravst-ci
