version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci --no-audit
      - npx tsc
  build:
    commands:
      - npx cdk deploy --trace -v --require-approval never '*'
