version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Next will install Node.js 18
      - n 18
      - npm install --global npm
      - npm ci --no-audit
  build:
    commands:
      - npx cdk deploy --trace -v --require-approval never '*'
