version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - npm install -g npm@
    - npm ci --no-audit
    - npx tsc
  build:
    commands:
    - npm run build
    - export BUCKET=$(AWS_REGION=$AWS_REGION npx @nrfcloud/aws-cf-stack-output $BIFRAVST_STACK_ID websiteBucketName)
    - aws s3 cp build s3://$BUCKET --recursive --metadata-directive REPLACE --cache-control 'public,max-age=600' --expires ''
