version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install --global npm
      - npm ci --no-audit
      - npx tsc
  build:
    commands:
      - node cli device-ui-config >
        $CODEBUILD_SRC_DIR_DeviceUI/.env.production.local
      - export INITIATOR_PIPELINE_NAME=`echo $CODEBUILD_INITIATOR | cut -d'/'
        -f2`
      - export SOURCE_VERSION=`aws codepipeline get-pipeline-state --name
        $INITIATOR_PIPELINE_NAME  | jq -r '.stageStates[0].actionStates[] |
        select(.actionName == "DeviceUISourceCode").currentRevision.revisionId'`
      - export VERSION=`git ls-remote --tags $SOURCE_REPO_URL | grep
        $SOURCE_VERSION | cut -d'/' -f3 | cut -d'^' -f1`
      - cat $CODEBUILD_SRC_DIR_DeviceUI/.env.production.local
      - export $(cat $CODEBUILD_SRC_DIR_DeviceUI/.env.production.local | xargs)
      - cd $CODEBUILD_SRC_DIR_DeviceUI/; npm ci --no-audit; npm run build;
      - aws s3 cp $CODEBUILD_SRC_DIR_DeviceUI/build
        s3://$SNOWPACK_PUBLIC_DEVICE_UI_BUCKET_NAME --recursive
        --metadata-directive REPLACE --cache-control 'public,max-age=600'
        --expires ''
      - aws cloudfront create-invalidation --distribution-id
        $SNOWPACK_PUBLIC_CLOUDFRONT_DISTRIBUTION_ID_DEVICE_UI --paths
        /,/index.html
