version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    - npm install -g npm@
    - npm ci --no-audit
    - npx tsc
  build:
    commands:
    - node dist/scripts/print-react-app-configuration.js > $CODEBUILD_SRC_DIR_BifravstApp/.env.production.local
    - cat $CODEBUILD_SRC_DIR_BifravstApp/.env.production.local
    - export $(cat $CODEBUILD_SRC_DIR_BifravstApp/.env.production.local | xargs)
    - cd $CODEBUILD_SRC_DIR_BifravstApp/; npm ci --no-audit; npm run build;
    - aws s3 cp $CODEBUILD_SRC_DIR_BifravstApp/build s3://$REACT_APP_WEBSITE_BUCKET_NAME --recursive --metadata-directive REPLACE --cache-control 'public,max-age=600' --expires ''
