version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Next will install Node.js 16
      - n 16
      - npm install --global npm
      - npm ci --no-audit
      - npx tsc
  build:
    commands:
      - $(node cli web-app-config)
      - export INITIATOR_PIPELINE_NAME=`echo $CODEBUILD_INITIATOR | cut -d'/'
        -f2`
      - export SOURCE_VERSION=`aws codepipeline get-pipeline-state --name
        $INITIATOR_PIPELINE_NAME  | jq -r '.stageStates[0].actionStates[] |
        select(.actionName == "WebAppSourceCode").currentRevision.revisionId'`
      - export PUBLIC_VERSION=`git ls-remote --tags $SOURCE_REPO_URL | grep
        $SOURCE_VERSION | cut -d'/' -f3 | cut -d'^' -f1`
      - export PUBLIC_VERSION=${PUBLIC_VERSION:-$SOURCE_VERSION}
      - export PUBLIC_URL="https://$PUBLIC_WEB_APP_DOMAIN_NAME"
      - cd $CODEBUILD_SRC_DIR_WebApp/; npm ci --no-audit; npm run build
      - aws s3 cp $CODEBUILD_SRC_DIR_WebApp/build s3://`echo
        $PUBLIC_WEB_APP_BUCKET_NAME | tr -d '"'` --recursive
        --metadata-directive REPLACE --cache-control 'public,max-age=600'
        --expires ''
      - aws cloudfront create-invalidation --distribution-id `echo
        $PUBLIC_CLOUDFRONT_DISTRIBUTION_ID | tr -d '"'` --paths /,/index.html
