version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Next will install Node.js 20
      - n 20
      - npm install --global npm
      - npm ci --no-audit
  build:
    commands:
      - npx cdk deploy --trace -v --require-approval never '*'
