name: Ensure source code is properly formatted

on:
  push:
    branches: [saga]

permissions:
  contents: write
  pull-requests: write

jobs:
  style:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci --no-audit --ignore-scripts

      - name: Compile TypeScript for type checking
        run: npx tsc

      - name: Check source code with eslint
        run: npx eslint --fix --ext .js,.ts,.jsx,.tsx ./

      - name: Format source code with prettier
        run: npx prettier --write ./

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: auto-format source code"
          committer: "github-actions[bot] <actions@example.com>"
          author: "github-actions[bot] <actions@example.com>"
          branch: format-source
          delete-branch: true
          title: "Auto-format source"
          body: "Ensure source code is properly formatted"
          labels: enhancement
